services:
  backend:
    build: .
    image: backend-devops
    environment:
      - SENTRY_DSN=https://2d0691ac855374da9f0002656d87a858@o4510355920846848.ingest.de.sentry.io/4510355996606544
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/test
      - BASE_URL=https://short.io/r/
    networks:
      - default
      - dev-net
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    image: frontend-devops
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - backend
      - frontend

networks:
  dev-net:
    external: true
    name: dev-net