FROM node:25-alpine3.22

WORKDIR /app

RUN apk add --no-cache nginx curl

COPY nginx.conf /etc/nginx/nginx.conf

COPY bin/start.sh /app/bin/start.sh

RUN chmod +x /app/bin/start.sh
# # Принимаем аргумент
# ARG API_URL=http://localhost/api
# # Устанавливаем как ENV переменную
# ENV API_URL=${API_URL}
RUN npm install @hexlet/project-devops-deploy-crud-frontend

EXPOSE 80

CMD ["/app/bin/start.sh"]
# CMD [ "npx", "start-hexlet-devops-deploy-crud-frontend"]